port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
proxies:
- name: configLINE5-55cb
  type: vless
  server: 172.66.40.99
  port: 443
  uuid: aa2339ea-3867-4dc2-8de8-59a4b1cce37e
  udp: true
  tls: true
  network: ws
  servername: hE136.maShkesTan.CoM
  ws-opts:
    path: /telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE?ed=2048
    headers:
      Host: hE136.maShkesTan.CoM
  reality-opts: null
- name: Channel_id_ShadowProxy66-cb42
  type: vless
  server: 188.68.53.100
  port: 6666
  uuid: 0abf9050-c7be-464d-80af-24094c2b97de
  udp: true
  tls: true
  network: tcp
  servername: Tgju.org
  ws-opts: null
  reality-opts:
    public-key: S_2bepGaT7EHeH5DdyEgio421RTgrAvvOOQiaq8zV0g
    short-id: b525ecd2fc
- name: Channel_id_ShadowProxy66-3867
  type: vless
  server: 51.77.91.192
  port: 8081
  uuid: 91b77af9-6f06-4c22-9c0e-bdd8f63de158
  udp: true
  tls: true
  network: tcp
  servername: yahoo.com
  ws-opts: null
  reality-opts:
    public-key: KdvX1bbHtA4Y16IukcDsNiEJ9iKYk4BLlI7LDsV0iFU
    short-id: d5bfd6c4
- name: Channel_id_ShadowProxy66-0fbf
  type: vmess
  server: 57.129.28.65
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /linkvws
    headers:
      Host: kapelleng.com
- name: Channel_id_ShadowProxy66-70f1
  type: trojan
  server: 172.67.181.173
  port: 443
  password: f282b878-8711-45a1-8c69-5564172123c1
  udp: true
  sni: vpn.stupidworld.web.id
- name: ğ—šğ—²ğ—¿ğ—ºğ—®ğ—»ğ˜†__VConfing-6548
  type: vless
  server: 91.99.117.197
  port: 8443
  uuid: 7585c7f8-5e6a-411e-ecf1-31f9bc7d7e38
  udp: true
  tls: true
  network: grpc
  servername: www.cdn77.com
  ws-opts: null
  reality-opts:
    public-key: X1ZcgEvOoRWwMQHDd4VOVUsVc0clHdcRKwVgjV9VvWs
    short-id: ''
- name: Channel_id_ShadowProxy66-9fac
  type: vless
  server: 188.114.96.6
  port: 443
  uuid: 8df60790-c903-4661-b85d-64c0009378e5
  udp: true
  tls: true
  network: ws
  servername: F1.paRsa.fiLegEar-Sg.Me
  ws-opts:
    path: /Tel-@ShadowProxy66/?ed=2560
    headers:
      Host: F1.paRsa.fiLegEar-Sg.Me
  reality-opts: null
- name: gonabad_vpn_30-fb37
  type: vless
  server: 172.67.74.133
  port: 443
  uuid: 3d7dd548-5456-4f28-8019-393fbfab3312
  udp: true
  tls: true
  network: ws
  servername: app-stg.gopay.co.id.servpn.my.id
  ws-opts:
    path: /sg3/?-JKVPN_TELEGRAM_CHANEL_JKVPN_JKVPN_JKVPN
    headers:
      Host: app-stg.gopay.co.id.servpn.my.id
  reality-opts: null
- name: Channel_id_ShadowProxy66-2c5b
  type: vless
  server: 185.234.66.82
  port: 443
  uuid: b5e8bfe7-6cdb-402d-b243-1e0f53ebb582
  udp: true
  tls: true
  network: ws
  servername: null
  ws-opts:
    path: /jzmdpvws
    headers:
      Host: 185.234.66.82
  reality-opts: null
- name: By_EbraSha_vless-IL-a07d
  type: vless
  server: ilta-wzxrxkdhbjpnprhkkpplsjwawhssvollvxzdhqshiqckwdgrdm.orbnet.xyz
  port: 443
  uuid: 0e8a6896-ad90-4a3b-89a3-77d64aa409e2
  udp: true
  tls: true
  network: tcp
  servername: i2pd.website
  ws-opts: null
  reality-opts:
    public-key: YVDo7U4O-AT2fa5H9E7hyYHKgfZd1vB6UdbAf2ggWQE
    short-id: 55e6af1a35e64a98
- name: Channel_id_ShadowProxy66-9871
  type: vless
  server: 185.234.66.94
  port: 443
  uuid: 2b25cdb0-ecb2-4caa-910d-b2e5b2309ca3
  udp: true
  tls: true
  network: ws
  servername: null
  ws-opts:
    path: /tqjkmwws
    headers:
      Host: 185.234.66.94
  reality-opts: null
- name: Channel_id_ShadowProxy66-530a
  type: vless
  server: 185.234.66.93
  port: 443
  uuid: e7d08833-b87f-4e9f-9f48-38485e58155e
  udp: true
  tls: true
  network: ws
  servername: null
  ws-opts:
    path: /zqpahpws
    headers:
      Host: 185.234.66.93
  reality-opts: null
- name: Channel_id_ShadowProxy66-62df
  type: vless
  server: ip.sb
  port: 443
  uuid: 8df60790-c903-4661-b85d-64c0009378e5
  udp: true
  tls: true
  network: ws
  servername: F1.paRsa.fiLegEar-Sg.Me
  ws-opts:
    path: /?ed=2560
    headers:
      Host: f1.parsa.filegear-sg.me
  reality-opts: null
- name: Channel_id_ShadowProxy66-0a2f
  type: vless
  server: laravel.com
  port: 443
  uuid: a0ac9cf5-f8c8-43cf-a09b-908455fb2b4b
  udp: true
  tls: true
  network: ws
  servername: rAyAn-cOnFiG-08.rAyAn-iIi.dNs-dYnAmIc.nEt
  ws-opts:
    path: /@ShadowProxy66
    headers:
      Host: rayan-config-08.rayan-iii.dns-dynamic.net
  reality-opts: null
- name: Channel_id_ShadowProxy66-626e
  type: vless
  server: 195.42.233.135
  port: 443
  uuid: 60216396-9001-451a-aa7b-8e57bb4c6b50
  udp: true
  tls: true
  network: ws
  servername: null
  ws-opts:
    path: /pfrlouws
    headers:
      Host: 195.42.233.135
  reality-opts: null
- name: Channel_id_ShadowProxy66-fa3e
  type: vmess
  server: 57.129.25.20
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: linkvws
    headers:
      Host: 57.129.25.20
- name: v2ray_configs_pool-9f98
  type: vless
  server: amazon-4.cristiano.name.ng
  port: 443
  uuid: 4c26ebc3-7784-46d8-b52a-7b0ccae6f4b4
  udp: true
  tls: true
  network: tcp
  servername: store.steampowered.com
  ws-opts: null
  reality-opts:
    public-key: TGlPtfVzGIVpMauPRMGJj2Uu6GUiCpu5ZizIIjw-wx4
    short-id: f5
- name: configLINE4-1a1b
  type: vless
  server: 172.66.40.99
  port: 443
  uuid: f12306c3-40f7-4543-afd0-534a91b1cdf3
  udp: true
  tls: true
  network: ws
  servername: hE136.maShkesTan.CoM
  ws-opts:
    path: /telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE?ed=2048
    headers:
      Host: hE136.maShkesTan.CoM
  reality-opts: null
- name: Channel_id_ShadowProxy66-68b8
  type: vless
  server: 104.26.8.156
  port: 443
  uuid: c4587bda-09fc-4b3b-8221-4450fccc33d1
  udp: true
  tls: true
  network: ws
  servername: yx.yushan.dpdns.org
  ws-opts:
    path: /
    headers:
      Host: yx.yushan.dpdns.org
  reality-opts: null
- name: Channel_id_ShadowProxy66-7354
  type: vmess
  server: 146.59.55.50
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /linkvws
    headers:
      Host: o.metuji.com
- name: Channel_id_ShadowProxy66-7359
  type: vmess
  server: 57.129.64.238
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /linkvws
    headers:
      Host: kapelleng.com
- name: Channel_id_ShadowProxy66-05a9
  type: vless
  server: 77.239.109.216
  port: 34045
  uuid: d8dd94fd-540e-461d-b5d4-acebef02c22a
  udp: true
  tls: true
  network: tcp
  servername: visit-this-invitation-link-to-join-tg-enkelte-notif.ekt.me
  ws-opts: null
  reality-opts:
    public-key: cDaDzPr3PlS3NM8lreHZbdo-Mhqz8vMBzMSkHXhGIUA
    short-id: e8ab71d0
- name: 2httpstmeConfigX2ray-8dc1
  type: vless
  server: 172.66.40.99
  port: 443
  uuid: f12306c3-40f7-4543-afd0-534a91b1cdf3
  udp: true
  tls: true
  network: ws
  servername: hE136.maShkesTan.CoM
  ws-opts:
    path: /telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE?ed=2048
    headers:
      Host: hE136.maShkesTan.CoM
  reality-opts: null
- name: Join_proxie_for_more-d0dc
  type: vless
  server: 104.21.62.144
  port: 443
  uuid: 9e843f2e-a992-438e-89a4-4f5c2606d856
  udp: true
  tls: true
  network: xhttp
  servername: sauron.melkore.ir
  ws-opts: null
  reality-opts: null
- name: Channel_id_ShadowProxy66-90cd
  type: vless
  server: kraken.com
  port: 443
  uuid: 3498b967-319f-436a-9edd-12f6ede84572
  udp: true
  tls: true
  network: ws
  servername: rAyAn-cOnFiG-02.rAyAn.dNs-dYnAmIc.nEt
  ws-opts:
    path: /@ShadowProxy66
    headers:
      Host: rayan-config-02.rayan.dns-dynamic.net
  reality-opts: null
- name: Ú©Ø§Ù†ÙÛŒÚ¯_Ø±ÙˆØ²Ø§Ù†Ù‡proxie-bdd7
  type: vmess
  server: 104.21.62.144
  port: 443
  uuid: 79e0b95b-0775-4bb5-87a9-9f1c9ada42c5
  alterId: 0
  cipher: zero
  tls: true
  network: xhttp
  udp: true
  ws-opts: null
- name: By_EbraSha_ss-PT-8ac1
  type: ss
  server: 185.231.233.173
  port: 990
  cipher: chacha20-ietf-poly1305
  password: f8f7aCzcPKbsF8p3
  udp: true
- name: ConfigX2ray-21e4
  type: vless
  server: 172.66.40.99
  port: 443
  uuid: telegram-id-Arfilter
  udp: true
  tls: true
  network: ws
  servername: rSa.2SeDkFjEuIxIjD0Ew9DvKcxoisiEk61.BlOg
  ws-opts:
    path: /telegram-ArV2ray,telegram-ArV2ray,telegram-ArV2ray,telegram-ArV2ray,telegram-ArV2ray,telegram-ArV2ray,telegram-ArV2ray,telegram-ArV2ray,telegram-ArV2ray,telegram-ArV2ray,telegram-ArV2ray,telegram-ArV2ray?ed=2048
    headers:
      Host: rSa.2SeDkFjEuIxIjD0Ew9DvKcxoisiEk61.BlOg
  reality-opts: null
- name: Channel_id_ShadowProxy66-de12
  type: vless
  server: servpn.my.id
  port: 443
  uuid: 69050db0-292b-4b33-a15d-a1780c07e7bb
  udp: true
  tls: true
  network: ws
  servername: servpn.my.id
  ws-opts:
    path: /sg4/?--@ShadowProxy66
    headers:
      Host: servpn.my.id
  reality-opts: null
- name: Channel_id_ShadowProxy66-68a8
  type: vless
  server: 185.242.87.162
  port: 443
  uuid: 35b0de8b-b156-43ff-a0e6-59f1018f7adb
  udp: true
  tls: true
  network: ws
  servername: null
  ws-opts:
    path: /holhclws
    headers:
      Host: 185.242.87.162
  reality-opts: null
- name: Channel_id_ShadowProxy66-9eda
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 2096
  uuid: e999db7a-1b17-4da6-bc37-c9fa24af2e93
  udp: true
  tls: true
  network: ws
  servername: 2J3e3G15lI.lIrA0xC8.iNfO
  ws-opts:
    path: /
    headers:
      Host: 2J3e3G15lI.lIrA0xC8.iNfO
  reality-opts: null
- name: Channel_id_ShadowProxy66-5fe7
  type: vless
  server: 104.26.4.90
  port: 443
  uuid: d88937d0-ce43-4bf8-9df6-d632810ba9ff
  udp: true
  tls: true
  network: ws
  servername: 007.xingfu.qzz.io
  ws-opts:
    path: /
    headers:
      Host: 007.xingfu.qzz.io
  reality-opts: null
- name: vless-ad260bb2
  type: vless
  server: bakrie.ac.id.servpn.my.id
  port: 443
  uuid: 4181c93f-0a91-48e3-bf9d-0e2c548734a5
  udp: true
  tls: true
  network: ws
  servername: bakrie.ac.id.servpn.my.id
  ws-opts:
    path: /id5?@
    headers:
      Host: bakrie.ac.id.servpn.my.id
  reality-opts: null
- name: Channel_id_ShadowProxy66-e401
  type: vmess
  server: 57.129.28.69
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /linkvws
    headers:
      Host: baradiha.com
- name: Channel_id_ShadowProxy66-52c3
  type: vless
  server: a.de.maviks.ru
  port: 443
  uuid: 0cc4d574-cf58-4c8e-a759-3aa1f919f34b
  udp: true
  tls: true
  network: tcp
  servername: www.microsoft.com
  ws-opts: null
  reality-opts:
    public-key: lyLhdojpACv6B3tHViJvPjNGATedXYRMnpAt4n4Siyo
    short-id: f203719d3ff9a5f5
- name: Channel_id_ShadowProxy66-df48
  type: vless
  server: zula.ir
  port: 443
  uuid: 172ed5fd-83a6-469e-863c-50e251a6c17d
  udp: true
  tls: true
  network: ws
  servername: rayan-supra.parisa.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: rayan-supra.parisa.dpdns.org
  reality-opts: null
- name: ğ—šğ—²ğ—¿ğ—ºğ—®ğ—»ğ˜†__VConfing-6f91
  type: vless
  server: 91.99.117.197
  port: 8443
  uuid: 4ec6a8f1-ce4d-49f6-e50e-4eb730a6ced3
  udp: true
  tls: true
  network: grpc
  servername: www.cdn77.com
  ws-opts: null
  reality-opts:
    public-key: X1ZcgEvOoRWwMQHDd4VOVUsVc0clHdcRKwVgjV9VvWs
    short-id: ''
- name: Channel_id_ShadowProxy66-f9ea
  type: vmess
  server: 51.79.86.182
  port: 42610
  uuid: e0957ca6-f613-4017-ff3c-effd1da8871a
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
  ws-opts: null
- name: Channel_id_ShadowProxy66-d36c
  type: vmess
  server: 38.99.82.193
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /linkvws
    headers:
      Host: tilebani.com
- name: Channel_id_ShadowProxy66-96bf
  type: vmess
  server: 135.125.182.74
  port: 28213
  uuid: 81852771-76fb-4e94-e4f1-4e37a698a49a
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
  ws-opts: null
- name: 210-c8cc
  type: vless
  server: 104.21.62.144
  port: 443
  uuid: 57bcea09-fb76-4e8b-b7e3-fd1862bbacd9
  udp: true
  tls: true
  network: xhttp
  servername: sauron.melkore.ir
  ws-opts: null
  reality-opts: null
- name: Ú©Ø§Ù†ÙÛŒÚ¯_Ø±ÙˆØ²Ø§Ù†Ù‡proxie-4d83
  type: vmess
  server: 104.21.62.144
  port: 443
  uuid: 9ec1787e-7919-475d-8c7f-976ebe92e299
  alterId: 0
  cipher: zero
  tls: true
  network: xhttp
  udp: true
  ws-opts: null
- name: By_EbraSha_ss-AT-a9f6
  type: ss
  server: 77.110.110.117
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 9JeYy8SkViXuSHVs9GFeSe
  udp: true
- name: Channel_id_ShadowProxy66-5f8e
  type: vmess
  server: 51.38.64.209
  port: 44023
  uuid: 7da457da-ed0f-437d-c81d-6c35885bbea3
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
  ws-opts: null
- name: Channel_id_ShadowProxy66-e573
  type: vmess
  server: 57.129.25.25
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /linkvws
    headers:
      Host: f.khilei.com
- name: Channel_id_ShadowProxy66-175d
  type: vless
  server: 188.114.96.6
  port: 443
  uuid: 8df60790-c903-4661-b85d-64c0009378e5
  udp: true
  tls: true
  network: ws
  servername: F1.paRsa.fiLegEar-Sg.Me
  ws-opts:
    path: /
    headers:
      Host: F1.paRsa.fiLegEar-Sg.Me
  reality-opts: null
- name: 209-fe2e
  type: vless
  server: 104.21.62.144
  port: 443
  uuid: 32015fc3-dc7f-46b8-b1a9-ccfc8b75fcde
  udp: true
  tls: true
  network: xhttp
  servername: sauron.melkore.ir
  ws-opts: null
  reality-opts: null
- name: Ú©Ø§Ù†ÙÛŒÙ†Ú¯_Ø±Ø§ÛŒÚ¯Ø§Ù†_Ú©Ø§Ù†Ø§Ù„_Gonabadvpnn_26-06a2
  type: vmess
  server: 64.227.45.92
  port: 20086
  uuid: 5e02bc01-42a7-4609-b20a-4d93feea65c6
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  udp: true
  ws-opts:
    path: /
    headers:
      Host: 64.227.45.92
- name: Channel_id_ShadowProxy66-02c3
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 443
  uuid: e999db7a-1b17-4da6-bc37-c9fa24af2e93
  udp: true
  tls: true
  network: ws
  servername: KlIi9Yc11L.lIrA0xC8.iNfO
  ws-opts:
    path: /
    headers:
      Host: KlIi9Yc11L.lIrA0xC8.iNfO
  reality-opts: null
- name: configLINE2-5cfb
  type: vless
  server: 172.66.40.99
  port: 443
  uuid: 8f06a3f8-ad6c-4852-83db-9a5d7649d15c
  udp: true
  tls: true
  network: ws
  servername: az52.mashkestan.com
  ws-opts:
    path: /telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE?ed=2048
    headers:
      Host: az52.mashkestan.com
  reality-opts: null
- name: Ú©Ø§Ù†ÙÛŒÙ†Ú¯_Ø±Ø§ÛŒÚ¯Ø§Ù†_Ú©Ø§Ù†Ø§Ù„_Gonabadvpnn_24-7d17
  type: vless
  server: 172.66.40.99
  port: 443
  uuid: 787c6fc8-aed8-4b4e-971b-e093cbf1699e
  udp: true
  tls: true
  network: ws
  servername: az52.mashkestan.com
  ws-opts:
    path: /telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE,telegram-CONFiGLiNE?ed=2048
    headers:
      Host: az52.mashkestan.com
  reality-opts: null
- name: Channel_id_ShadowProxy66-4438
  type: vmess
  server: 57.129.24.125
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /linkvws
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - âš¡ Auto-Select
  - DIRECT
  - configLINE5-55cb
  - Channel_id_ShadowProxy66-cb42
  - Channel_id_ShadowProxy66-3867
  - Channel_id_ShadowProxy66-0fbf
  - Channel_id_ShadowProxy66-70f1
  - ğ—šğ—²ğ—¿ğ—ºğ—®ğ—»ğ˜†__VConfing-6548
  - Channel_id_ShadowProxy66-9fac
  - gonabad_vpn_30-fb37
  - Channel_id_ShadowProxy66-2c5b
  - By_EbraSha_vless-IL-a07d
  - Channel_id_ShadowProxy66-9871
  - Channel_id_ShadowProxy66-530a
  - Channel_id_ShadowProxy66-62df
  - Channel_id_ShadowProxy66-0a2f
  - Channel_id_ShadowProxy66-626e
  - Channel_id_ShadowProxy66-fa3e
  - v2ray_configs_pool-9f98
  - configLINE4-1a1b
  - Channel_id_ShadowProxy66-68b8
  - Channel_id_ShadowProxy66-7354
  - Channel_id_ShadowProxy66-7359
  - Channel_id_ShadowProxy66-05a9
  - 2httpstmeConfigX2ray-8dc1
  - Join_proxie_for_more-d0dc
  - Channel_id_ShadowProxy66-90cd
  - Ú©Ø§Ù†ÙÛŒÚ¯_Ø±ÙˆØ²Ø§Ù†Ù‡proxie-bdd7
  - By_EbraSha_ss-PT-8ac1
  - ConfigX2ray-21e4
  - Channel_id_ShadowProxy66-de12
  - Channel_id_ShadowProxy66-68a8
  - Channel_id_ShadowProxy66-9eda
  - Channel_id_ShadowProxy66-5fe7
  - vless-ad260bb2
  - Channel_id_ShadowProxy66-e401
  - Channel_id_ShadowProxy66-52c3
  - Channel_id_ShadowProxy66-df48
  - ğ—šğ—²ğ—¿ğ—ºğ—®ğ—»ğ˜†__VConfing-6f91
  - Channel_id_ShadowProxy66-f9ea
  - Channel_id_ShadowProxy66-d36c
  - Channel_id_ShadowProxy66-96bf
  - 210-c8cc
  - Ú©Ø§Ù†ÙÛŒÚ¯_Ø±ÙˆØ²Ø§Ù†Ù‡proxie-4d83
  - By_EbraSha_ss-AT-a9f6
  - Channel_id_ShadowProxy66-5f8e
  - Channel_id_ShadowProxy66-e573
  - Channel_id_ShadowProxy66-175d
  - 209-fe2e
  - Ú©Ø§Ù†ÙÛŒÙ†Ú¯_Ø±Ø§ÛŒÚ¯Ø§Ù†_Ú©Ø§Ù†Ø§Ù„_Gonabadvpnn_26-06a2
  - Channel_id_ShadowProxy66-02c3
  - configLINE2-5cfb
  - Ú©Ø§Ù†ÙÛŒÙ†Ú¯_Ø±Ø§ÛŒÚ¯Ø§Ù†_Ú©Ø§Ù†Ø§Ù„_Gonabadvpnn_24-7d17
  - Channel_id_ShadowProxy66-4438
- name: âš¡ Auto-Select
  type: url-test
  proxies:
  - configLINE5-55cb
  - Channel_id_ShadowProxy66-cb42
  - Channel_id_ShadowProxy66-3867
  - Channel_id_ShadowProxy66-0fbf
  - Channel_id_ShadowProxy66-70f1
  - ğ—šğ—²ğ—¿ğ—ºğ—®ğ—»ğ˜†__VConfing-6548
  - Channel_id_ShadowProxy66-9fac
  - gonabad_vpn_30-fb37
  - Channel_id_ShadowProxy66-2c5b
  - By_EbraSha_vless-IL-a07d
  - Channel_id_ShadowProxy66-9871
  - Channel_id_ShadowProxy66-530a
  - Channel_id_ShadowProxy66-62df
  - Channel_id_ShadowProxy66-0a2f
  - Channel_id_ShadowProxy66-626e
  - Channel_id_ShadowProxy66-fa3e
  - v2ray_configs_pool-9f98
  - configLINE4-1a1b
  - Channel_id_ShadowProxy66-68b8
  - Channel_id_ShadowProxy66-7354
  - Channel_id_ShadowProxy66-7359
  - Channel_id_ShadowProxy66-05a9
  - 2httpstmeConfigX2ray-8dc1
  - Join_proxie_for_more-d0dc
  - Channel_id_ShadowProxy66-90cd
  - Ú©Ø§Ù†ÙÛŒÚ¯_Ø±ÙˆØ²Ø§Ù†Ù‡proxie-bdd7
  - By_EbraSha_ss-PT-8ac1
  - ConfigX2ray-21e4
  - Channel_id_ShadowProxy66-de12
  - Channel_id_ShadowProxy66-68a8
  - Channel_id_ShadowProxy66-9eda
  - Channel_id_ShadowProxy66-5fe7
  - vless-ad260bb2
  - Channel_id_ShadowProxy66-e401
  - Channel_id_ShadowProxy66-52c3
  - Channel_id_ShadowProxy66-df48
  - ğ—šğ—²ğ—¿ğ—ºğ—®ğ—»ğ˜†__VConfing-6f91
  - Channel_id_ShadowProxy66-f9ea
  - Channel_id_ShadowProxy66-d36c
  - Channel_id_ShadowProxy66-96bf
  - 210-c8cc
  - Ú©Ø§Ù†ÙÛŒÚ¯_Ø±ÙˆØ²Ø§Ù†Ù‡proxie-4d83
  - By_EbraSha_ss-AT-a9f6
  - Channel_id_ShadowProxy66-5f8e
  - Channel_id_ShadowProxy66-e573
  - Channel_id_ShadowProxy66-175d
  - 209-fe2e
  - Ú©Ø§Ù†ÙÛŒÙ†Ú¯_Ø±Ø§ÛŒÚ¯Ø§Ù†_Ú©Ø§Ù†Ø§Ù„_Gonabadvpnn_26-06a2
  - Channel_id_ShadowProxy66-02c3
  - configLINE2-5cfb
  - Ú©Ø§Ù†ÙÛŒÙ†Ú¯_Ø±Ø§ÛŒÚ¯Ø§Ù†_Ú©Ø§Ù†Ø§Ù„_Gonabadvpnn_24-7d17
  - Channel_id_ShadowProxy66-4438
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- MATCH,PROXY
